### PR TITLE
Improved logit inclusion

### PR DESCRIPTION
**Pull request by ben-farnham**
Hi,
So, a surprising amount of changes here - managing a cross platform build with cmake is not straight forward: Some things that work on windows do not seem to work on linux and vice-versa. All rather irritating.

Anyway, the changes in this branch focus on 2 features, both build related, and both related to build the compat layer as a stand-alone module (its 'in-quasar build' should be unchanged)
1. How the compat lib builds with LogIt, options for LogIt are
   - as source code, cloned, built and linked as part of the compat lib.
   - as a static lib, built elsewhere
   - as a shared lib, built elsewhere
   The main build logic is handled in the '_Resolve LogIt library_' section of the compat layer's _CMakeLists.txt_
2. How the compat layer build handles boost.
   - I've added 2 sample files _custom_boost_cc7.cmake_ and _custom_boost_win_VS2017.cmake_. These use cmake find_library to locate the compiled boost libraries (I tried findboost, did not manage to get it to work). 
  - the custom boost loader file is set at the cmake invocation with -DCMAKE_TOOLCHAIN_FILE=custom_boost_cc7.cmake (using that file as an example). Note that the cmake files I added only do boost specific stuff, but, as with quasar, you could do any platform specific stuff in there.

So, take a look. Please let me know what you think.

Some example build invocations are:

> cmake -DSTANDALONE_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=custom_boost_cc7.cmake

> cmake -DSTANDALONE_BUILD=ON -DSTANDALONE_BUILD_SHARED=ON -DCMAKE_TOOLCHAIN_FILE=custom_boost_cc7.cmake

Cheers,
Ben

### CODE REVIEW

**Comment by ben-farnham** [comment]
And another thing...

To get stand-alone LogIt, this should be built from:
* repo: https://ben-farnham@github.com/quasar-team/LogIt.git
* branch: stand-alone-LogIt-with-strings-V3

The branch is required until it gets merged to the master.

Cheers,
Ben

**Comment by pnikiel** [comment]
Hi @ben-farnham ,

before I go into detailed review, just wanted to give it a brief try to get the feeling.

(1) I notice that build_standalone.py is not able to accept toolchain(build config) file - I think this should be fixed,
(2) so even when I passed it:

-- !!! *** WARNING *** !!! currently cloning quasar-team/LogIt with a dev branch - remove any instances of branch specifier [stand-alone-LogIt-with-strings-V3] in this file once LogIt's dev branch merged to master
Cloning into 'LogIt'...
remote: Counting objects: 124, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 124 (delta 60), reused 57 (delta 27), pack-reused 26
Receiving objects: 100% (124/124), 56.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (70/70), done.
CMake Error at CMakeLists.txt:90 (add_subdirectory):
  add_subdirectory given source
  "/home/pnikiel/gitProjects/open62541-compat/LogIt" which is not an existing
  directory.


-- LogIt added as compiled object code from sub-directory LogIt
CMake Error at CMakeLists.txt:113 (message):
  Cannot build with LogIt.  No LogIt include directory found at
  [/home/pnikiel/gitProjects/open62541-compat/LogIt/include].  If building
  with LogIt as external shared/static library this must be specified using
  -DLOGIT_INCLUDE_DIR=path.  Path can be absolute or relative to
  [/home/pnikiel/gitProjects/open62541-compat/]


-- Configuring incomplete, errors occurred!
See also "/home/pnikiel/gitProjects/open62541-compat/build/CMakeFiles/CMakeOutput.log".

could I ask you to confirm that it builds in a fresh directory on your Linux machine?
Could you maybe update README.md if any less obvious actions are required?

**Comment by ben-farnham** [comment]
think this should do it (obviously with your own header/libs paths for boost)

> git clone -b improved-logit-inclusion https://github.com/quasar-team/open62541-compat.git
cd open62541-compat/
export BOOST_PATH_HEADERS=/local/bfarnham/workspace/boost_mapped_namespace_builder/work/MAPPED_NAMESPACE_INSTALL/64bit/include/
export BOOST_PATH_LIBS=/local/bfarnham/workspace/boost_mapped_namespace_builder/work/MAPPED_NAMESPACE_INSTALL/64bit/lib/
python prepare.py
cmake -DSTANDALONE_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=custom_boost_cc7.cmake
make clean && make

**Comment by pnikiel** [comment]
Hello Ben,
one step further now.
Similarly to what you did with custom_boost_..._.cmake files, would you be able to provide one which works with CC7- standard boost out of the box?
I tried to prepare it myself but naive attempts seem to fail (lib not found ) and i didn't really see the pattern how the discovered lib path is further on passed to CMake-based linking process...

(in any case, since CC7 is our agreed base, i think we should have such a file ...)

**Comment by ben-farnham** [comment]
I've added one, try with `-DCMAKE_TOOLCHAIN_FILE=boost_standard_install_cc7.cmake `

**Comment by pnikiel** [comment]
Hi Ben,

greatly appreciating that you added the standard CC7 file ;-)

But it still fails ... did you really try the same recipe on standard CC7?

$ cmake -DSTANDALONE_BUILD=ON -DCMAKE_TOOLCHAIN_FILE=boost_standard_install_cc7.cmake 
-- Using file [boost_standard_install_cc7.cmake] toolchain file
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_SUFFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_SUFFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_SUFFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_SUFFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_SUFFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_FIND_LIBRARY_PREFIXES
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.

**Comment by ben-farnham** [comment]
Man, this is _so_ irritating. I really did try it on my cc7 machine, and it really worked. Wind must have been blowing from right direction or something equally un-reproducible. Let me have a fiddle about and see if I can see the same error...

hmm

**Comment by pnikiel** [comment]
I'm really sorry to hear this and I do imagine it might be infuriating. But I'm just trying to seriously review ... (and actually test before i review)

**Comment by ben-farnham** [comment]
I know, and thanks - your review is much appreciated. My irritation is directed solely at cmake.

**Comment by pnikiel** [comment]
do you think it might be related to me running the default cmake 2.8 while perhaps you alias it to cmake 3.x?

**Comment by ben-farnham** [comment]
Aha - I deleted my open62541-compat directory and re-cloned from github. Now I get the same error, in fact I can't not get the error. So, this must be what progress looks like...

**Comment by ben-farnham** [comment]
OK, ready I think.

Have a look at the first 2 examples on the README for building open62541-compat as
a) static stand-alone lib
b) shared stand-alone lib
Both with LogIt 'built-in' to the library.

I'll add some examples of cmake invocations with LogIt as an external library too, but not tonight. I've run out of time.

Cheers!

**Comment by ben-farnham** [comment]
Just one additional thing I'd like your opinion on please - it's more of an approach than straight technical per se. In this branch I've removed the need to run prepare.py (and I removed it from the README too); the clone and build of open62541 is done directly in the CMakeLists.txt
`
clone_open62541()
build_open62541()
`

Reason: on windows cmake knows exactly which visual studio version the build will use (via the -G option) and therefore it is well placed to execute the build. Prepare.py on the other hand uses a hardcoded path which 
a) dictates the visual studio version to use
`CMD_loadVisStu12Env = '"C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat"`
b) dictates the installation path too
All seems rather restrictive and failure prone for usage on external users machines.

So, take a look and let me know: Now, when cmake is called to generate the makefiles (or visual studio solution), it clones and builds open62541 so that the library is ready to go.

**Comment by pnikiel** [comment]
Hi Ben,

I've tested the STANDALONE mode and it seems to build well in inside-source-tree location. Great documentation, very appreciated!

What didn't work is the out-of-source build, i.e. when I create a directory called "build" and run cmake from inside "build". I think it is rather a standard practice so I'd like this to work - and I think we should advocate building inside "build" rather than in the parent dir.

I tried to understand why it fails and realized that a little fix might be necessary, which I'm contributing here:

https://github.com/quasar-team/open62541-compat/compare/improved-logit-inclusion...improved-logit-inclusion-pn

Could you perhaps consider it?

**Comment by pnikiel** [comment]
Plus, shall we remove prepare.py and build_standalone.py?
With your improvements they lose their raison d'etre.

**Comment by pnikiel** [comment]
Hello Ben,
one more thing - I tested how it works with Quasar, as open62541-compat module. 
There are some things to fix, because right now it no longer works out of the shelf.
You moved cloning logic to git (which seems a good thing to me) from build_standalone.py but paths changed too and our standard open62541_config.cmake from quasar no longer holds. So
(1) we fix the paths,
(2) we change the open62541_config.cmake file

**Comment by ben-farnham** [comment]
Hi Piotr,

OK - ready I think....
1. I merged your branch (improved-logit-inclusion-pn) to this branch (improved-logit-inclusion).
2. I did a little more work on the examples and README.md, testing that the command lines we claim in the examples genuinely work on windows etc (and I am happy to confirm that they do).

As regards quasar, this is where it becomes a bit of a tangle. I'll try and explain (though maybe a phone call is the best).
1. I'd like to retire quasar/LogIt -> stand alone Logit becomes the **'one true LogIt'**.
2. quasar should then include the one true LogIt as a 'non-optional' module.
3. The one true LogIt should merge branch 'stand-alone-LogIt-with-strings-V3' -> 'master'

Further down the line (not this merge), quasar should also have the option to accept LogIt as an externally built library too. But, this merge/update/etc looks complicated enough without that dimension.

**Comment by ben-farnham** [comment]
OK, following our phone calls, final outcome is
## I will
1. **Tag** open62541-compat master branch with (quasar_compatible_up_to_v1.2.1). Just to have a fixed point to view/roll back to if needed.
2. **Merge** Stand-alone LogIt: branch stand-alone-LogIt-with-strings-V3 -> master.
2. **Merge** open62541-compat: branch improved-logit-inclusion ->master (i.e. this pull request).

**Comment by ben-farnham** [comment]
Pre-merge tag:
[quasar_compatible_up_to_v1.2.1](https://github.com/quasar-team/open62541-compat/releases/tag/quasar_compatible_up_to_v1.2.1).

**Pull request merged**
