### PR TITLE
Arrays for open62541-compat

### PR DESCRIPTION
**Pull request by pnikiel**
This feature branch will probably be extended over time, however since it is in decent shape and already functional, I'd very much ask for a review.

### CODE REVIEW

**Comment by ben-farnham** [comment]
Had a look through the code, didn't see anything to cause concern. 

Before giving it the final OK I'd like to actually try running the code, but I'm a bit confused about what branches go with what...

To try this I guess I need to:
1. clone quasar (branch - arrays4)
2. add open62541-compat as an optional module (this branch)
3. design a server with whatever arrays I want to test (+ generate + build + run)

Are the branch specifiers above correct?

**Comment by pnikiel** [comment]
I believe that you are right.

**Comment by ben-farnham** [comment]
ok, here goes - wish me luck!

**Comment by ben-farnham** [comment]
Hmm,

Using the plan as specified above (quasar: arrays4 & open62541-compat:pnikiel-arrays) I get a build error in a freshly generated project.

Investigation shows that the AddressSpace module (where the build fails) includes these directories from the compat directory
```
-- AddressSpace include dir='open62541-compat/include'
-- AddressSpace include dir=open62541-compat/open62541/include'
```
**however**
In the setup on my disk, the open62541.h amalgamated header is generated in a different folder
```
bash-4.2$ find . -name "open62541.h"
./open62541-compat/open62541/open62541.h
bash-4.2$ 
```
So, the build fails during AddressSpace as it tries to locate include <open62541.h>

**Comment by pnikiel** [comment]
Ben, could you please send me your reproduction scenario?
This is an excerpt of my bash history which resulted in a successful build, what is the difference among us?

 1012  ./quasar.py create_project /tmp/quasar-test-ben
 1013  cd /tmp/quasar-test-ben/
 1014  ll
 1015  ./quasar.py list_enabled
 1016  ./quasar.py list_modules
 1017  ./quasar.py enable_module open62541-compat
 1018  ll
 1019  cp ~/gitProjects/quasar/open62541_config.cmake .
 1020  ll
 1021  ./quasar.py set_build_config open62541_config.cmake 
 1022  ./quasar.py build
 1023  ldd bin/OpcUaServer 
 1024  history
 1025  cd open62541-compat/
 1026  git checkout pnikiel-arrays 
 1027  cd ..
 1028  make

Note my quasar repo is at 
2da3f4c0800d718e7d0a614f195e5d37cbb31a06
which corresponds to v1.2.2.

let me know

**Comment by ben-farnham** [comment]
I have a functioning build now after making changes to my open6 toolchain file (left side is original). That may be a concern for existing users.

image

**Comment by pnikiel** [comment]
FYI this I reported to you after your changes in the open62541-compat CMake rework  ;-)
this is why I asked to tag the last working open62541-compat with that "works_up_to_quasar_1.2.2" which we did together ;-)
glad you managed to move on !

**Comment by ben-farnham** [comment]
So _that's_ what we were doing!

**Comment by ben-farnham** [comment]
Next up: Generated the 3 classes in the Design.xml below. Compliation fails (error pasted at the bottom of this post).

```
  1 <?xml version="1.0" encoding="UTF-8"?>
  2 <d:design projectShortName="" xmlns:d="http://cern.ch/quasar/Design"
  3         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  4         xsi:schemaLocation="http://cern.ch/quasar/Design Design.xsd ">
  5 
  6         <d:class name="ConfigurationArrays">
  7                 <d:devicelogic/>
  8                 <d:configentry dataType="OpcUa_Int32" name="configurationArrayInt32">
  9                         <d:array minimumSize="3" maximumSize="3" />
 10                 </d:configentry>
 11         </d:class>
 12 
 13         <d:class name="Controller">
 14                 <d:devicelogic />
 15                 <d:cachevariable name="runIncrementer" initializeWith="valueAndStatus"
 16                         dataType="OpcUa_Boolean" nullPolicy="nullForbidden" addressSpaceWrite="delegated"
 17                         initialStatus="OpcUa_BadWaitingForInitialData" initialValue="OpcUa_False" />
 18                 <d:cachevariable name="incrementCounter"
 19                         initializeWith="valueAndStatus" dataType="OpcUa_UInt32" nullPolicy="nullForbidden"
 20                         addressSpaceWrite="forbidden" initialStatus="OpcUa_BadWaitingForInitialData"
 21                         initialValue="0" />
 22                 <d:cachevariable name="incrementPeriodMs"
 23                         initializeWith="valueAndStatus" dataType="OpcUa_UInt32" nullPolicy="nullForbidden"
 24                         addressSpaceWrite="delegated" initialStatus="OpcUa_BadWaitingForInitialData"
 25                         initialValue="1000" />
 26         </d:class>
 27 
 28         <d:class name="ReadoutArrays">
 29                 <d:devicelogic/>
 30                 <d:cachevariable name="readoutArrayInt32"
 31                         addressSpaceWrite="forbidden" initializeWith="valueAndStatus"
 32                         nullPolicy="nullAllowed" dataType="OpcUa_Int32" initialValue="0" initialStatus="OpcUa_BadWaitingForInitialData">
 33                         <d:array minimumSize="3" />
 34                 </d:cachevariable>
 35         </d:class>
 36 
 37         <d:root>
 38                 <d:hasobjects instantiateUsing="configuration" class="ConfigurationArrays"/>
 39         </d:root>
 40 
 41 </d:design>
```

compile error is
image

**Comment by pnikiel** [comment]
Ben,
my understanding is that this comes from questionable state of the arrays4 branch rather than from open62541-compat arrays. Since I agreed with ML to take over arrays4 integration, I'd like to ask you that right now we focus solely on open62541-compat and the interaction of both things (o6-compat + quasar arrays) we try later.

FYI in the TE-CRG server I made a lot of local changes in quasar to make it compile with o6-compat (this branch) - they will end up in quasar in the end.

**Comment by ben-farnham** [comment]
Note that the same Design.xml generation *does* build with the unified automation backend. So, this presumably is related to the open62541-compat module.

**Comment by pnikiel** [comment]
I understand your point, by the choices taken by arrays4 currently are not necessarily optimal.
If you insist very much, I can consider adapting o6-compat further.
But since I'm already taking over a lot of someone's work, I'd prefer to address it in leaner way if arrays4 branch.
Let me know your viewpoint.

**Comment by ben-farnham** [comment]
No problem - I'm fine with validating the compat layer arrays implementation only. The reason I was trying with quasar (branch: arrays4) was solely to execute the arrays code of o6-compat, nothing more.

Question: how do I execute the o6-compat layer code without arrays in quasar?

**Comment by pnikiel** [comment]
Hi Ben,

if you like a quick dive, maybe you'd like to try one of non-quasar open62541-compat projects:
https://gitlab.cern.ch/atlas-dcs-opcua-servers/UaoClientForOpcUaSca/tree/master/demo

and then in main.cpp just try anything you like... all constructs of open62541-compat + open62541 should be available to you.

If you are willing to write some unit tests which would be unrelated to quasar, that could be great ;-)

**Comment by ben-farnham** [comment]
OK, added googletest support plus info in the README plus some tests to get us started (focused on arrays).
https://github.com/quasar-team/open62541-compat/commit/3a6a72d6e2866209ca6ca17f69608668ab26d3c4

One thing - if you take a look at test/src/arrays_test.cpp there is a test commented out at the bottom. I added this comment for you to take a look at

> Piotr - this test fails, I didn't expect that. Is that a bug or the test is not accurate? Coudl you take a look please

**Comment by pnikiel** [comment]
thanks, having a look right now.

**Comment by pnikiel** [comment]
I've looked into the following functions of open62541 which seem to constitute the backbone of open62541 array handling:
- UA_Variant_setArray,
- UA_Variant_setArrayCopy,
- UA_Array_copy
 none of them seem to support (or even be aware) of array dimensions ;-/ 
But they of course pay attention to arrayLength field.
I see the following possibilities now:
(1) we adapt to arrayLength instead of arrayDimensions as array indication (and our UaVariant::arrayDimensions wrapper accordingly) 
(2) we manually control arrayDimensions and arrayDimensionsSize inside UA_Variant structure whenever we manipulate one (e.g. create, copy, ...)

a very strong argument against (2) is that storing arrayDimensions itself requires dynamic memory handling, so if we create a 'manually-tinkered' UA_Variant (with arrayDimensions) and let it sink into open62541 managed ecosystem (which is what happens e.g. every time a setter is invoked - that means very often) AND open62541 is not particularly accustomed to arrayDimensions support, then we will have a leak.

I propose to go (1).

What do you think Ben?

**Comment by ben-farnham** [comment]
Probably out of my depth in open62541 knowledge TBH. I'll hazard an opinion anyway but feel free to override it.

Are these functions worth looking into ?
> UA_Variant_copyRange(const UA_Variant *src, UA_Variant *dst,
                     const UA_NumericRange range);
UA_Variant_setRange(UA_Variant *v, void *array,
                    size_t arraySize, const UA_NumericRange range);
UA_Variant_setRangeCopy(UA_Variant *v, const void *array,
                        size_t arraySize, const UA_NumericRange range);

They seem to take a *UA_NumericRange* which looks like it knows about multiple dimensions
>NumericRanges are used to indicate subsets of a (multidimensional) array. They no official data type in the OPC UA standard and are transmitted only with a string encoding, such as “1:2,0:3,5”. The colon separates min/max index and the comma separates dimensions. A single value indicates a range with a single element (min==max).

Or I missed the point?

**Comment by pnikiel** [comment]
I don't see how would you profit from Numeric Ranges to supply lack of array dimensions in UA_Array_copy etc.

**Comment by pnikiel** [comment]
Ben,
for your comment from this morning that you'd like to try open62541-compat arrays (this branch) with ML's arrays: here I pushed the integration branch for arrays for quasar, and it seems to work with both backends:

https://github.com/quasar-team/quasar/pull/42

you might be interested to check it.

**Comment by ben-farnham** [comment]
> I don't see how would you profit from Numeric Ranges to supply lack of array dimensions in UA_Array_copy etc.

I probably missed the point, I had recently read the line below from the [open62541 docs](https://open62541.org/doc/current/tutorial_server_method.html#increase-array-values-method) and thought it might apply to this situation.
> Each variant may in turn contain a (multi-dimensional) array or scalar of any data type.

Happy to move on with your approach so as not to block progress. 

My review is complete once that troublesome 3rd unit test either
a) passes
or
b) is deleted (with a convincing explanation as to why)

**Comment by pnikiel** [comment]
Hi Ben,
I'd like to keep the test (which currently fails) because in my opinion everything is right about it.
If we both agree we can go (1) then I'm leaving you the choice who implements that change in the lib itself (you or me). Decide and let me know.

**Comment by ben-farnham** [comment]
OK, lets do (1). Could you implement it? I think you understand the details better than me.

**Comment by pnikiel** [comment]
Hi Ben,
fixed, the test now passes.
Shall we merge?

**Comment by ben-farnham** [comment]
Great. Had a quick look at the _UaVariant::arrayDimensions_ implementation, looks good.

So yes - merge it!

**Pull request merged**
