### PR TITLE
Fix for windows compatibility

### PR DESCRIPTION
**Pull request by ben-farnham**
Two code changes
1. __PRETTY_FUNCTION__ is not known to MSVC; changed to __FUNCTION__
2. std::atomic_flag(ATOMIC_FLAG_INIT), apparently references a deleted function in MSVC. Here's [MS docs on their implementation of std::atomic_flag](https://msdn.microsoft.com/en-us/library/hh874636.aspx) and [here's a stackoverflow question/answer](https://stackoverflow.com/questions/28339054/simple-spinlock-with-atomic-does-not-compile) looking like the same problem.

### CODE REVIEW

**Comment by pnikiel** [comment]
Hi Ben,

how comes we see this only now? Did we hardcode some old open62541-compat version? The code is like 9 months old ;-)

**Comment by ben-farnham** [comment]
Hi Piotr, take a look at this please for a review. Basically the windows CI build has been building with a static tag of the compat module, not the master. Not good. 

The changes in this pull request are needed to build the master on windows.

**Comment by pnikiel** [comment]
Hi Ben,

on __PRETTY_FUNCTION__: we once wrote the following with Damian:

#ifndef __GNUC__
#define __PRETTY_FUNCTION__ __FUNCSIG__
#endif

I leave the judgement to you if __FUNCTION__ is as good.

I have no other comments, it looks OK to me.

**Comment by ben-farnham** [comment]
OK, I'll leave __FUNCTION__ for now - less code.

this code
```c++
LOG(Log::TRC) << __FUNCTION__ << " m_impl="<<m_impl<<" m_impl.data="<<m_impl->data;
```
outputs this
```
2017-06-01 14:28.07.148449 [uavariant.cpp:141, TRC] +UaVariant::~UaVariant m_impl=<blah...>
```

I'll make the merge. Thanks for the review.

Cheers,
Ben

**Pull request merged**
