### PR TITLE
Variant assignment fix

### PR DESCRIPTION
**Pull request by ben-farnham**
OK - _this_ time the pull request is intentional.

With the changes in this branch for the compat layer I am able to build and run the caen-opcua-server with an open62541 backend. Which I'm rather pleased with.

Cheers,
Ben

### CODE REVIEW

**Comment by pnikiel** [comment]
Hi Ben,
my additional comment (remaining ones were posted to pull req #2 ):
- is toFullString() behaviour compatible with UA's counterpart?
- is the type printed out readable? I think it will be a hex value  (pointer to a type definition), not so useful to a reader. Or?

**Comment by ben-farnham** [comment]
Hi Piotr,

Well, honestly the variant's toFullString() functionality is essentially a placeholder - without it the CAEN OPC_UA server simply cannot compile. I wasn't really intending this branch for deep uavariant development; rather to build and run a real server with Open6 (and Unified Automation).

I agree that there's plenty to do on the uavariant, probably the compat layer in general, but it's outwith the scope for these changes.

Cheers,
Ben

**Comment by pnikiel** [comment]
OK: but shall these changes stay solely on the branch (then of course everything is up to you) or are you willing to merge them to master (then I carefully review what enters master) ?
I've seen a merge request thus I thought the latter option is your intention.

**Comment by ben-farnham** [comment]
Merge to master. I haven't (intentionally) done anything CAEN specific; everything in this little feature branch is generic good stuff in the sense that all open6 uavariant users will benefit. I meant that I only implemented enough generic good stuff to get the CAEN server to build.

A review would be much appreciated.

**Comment by ben-farnham** [comment]
Ah, just read your comments from the (cancelled) pull request. Let me digest that...

**Comment by ben-farnham** [comment]
_1) (cosmetic) avoid "open6" term in code... this abbreviation is not meaningful to the world, it is just our convention. Use "open62541" if you like but IMO it is an overkill, so I'd just call things "variant" or so ... ( createVariant(), deleteVariant() static methods etc). And especially I'd avoid this term in the headers ;-) )_

Well - to my way of thinking, variables and methods should be named to hint to their intention: Given that there are instances of both open62541 variants and compat layer variants in play, I wanted the reader of the code to know which type was being captured by a variable, or created or deleted. I'll change to open62541*

_2) (serious) avoid diverting from UA API: i.e. changing constructor UaVariant(int v) to UaVariant (const int& v)._
Good point; will do.

_3) (serious) 
commenting-out of inclusion in uavariant.h
I don't get the point here. what's wrong? When it failed, did you compile with -std=c++0x ?_
Oops: I meant to clean this up, I forgot. I had a dreadful time with this code and I couldn't really grasp what various posts on the web had to say about it. It seems like stdatomic should, but doesn't, appear in the CC7 gcc version, or something. Let me try - I may come back on this one for assistance.

_4) (probably cosmetic) dropping of ASUtils.h, of course it is good provided it is actually not used; was this tested?_
It compiles and runs, things seem to work, I'm saying **yes**!

**Comment by ben-farnham** [comment]
image

This is what happens when I try building stdatomic/atomic thing. Any ideas?

**Comment by pnikiel** [comment]
Could you please do

make VERBOSE=1

and send me the output?

**Pull request merged**
