### PR TITLE
Profit from status codes descriptions from open62541-compat

### PR DESCRIPTION
**Pull request by parasxos**
https://its.cern.ch/jira/browse/OPCUA-931

### CODE REVIEW

**Comment by pnikiel** [comment]
Hi @parasxos, it's even better if we don't have to dig through open62541's internal data ;-)

It looks good to me, will test it tomorrow, two questions for now:
1. Can you verify that in case the error code is unknown, its hex representation is added by either of the functions you use,
2. Could you please verify that you don't need to compile Open6 with additional CMake's include which is sth like "ENABLE_STATUSCODES" or so? I remember that without it the table didn't get populated but maybe i'm completely wrong.
Both points will either way turn up in the testing but maybe you know the answer already.

**Comment by parasxos** [comment]
1. In case the status code is not in the table, now, it is only "Unknown" returned with an additional verbose explanation. I think you are right and the code should be printed as well. (TODO)
2. No need for recompilation in such case(UA_ENABLE_STATUSCODE_DESCRIPTIONS not defined), **but** the drawback would be that the table will not be populated and only the "unknown" status code as in point (1) will be available. Thats a 2nd reason for implementing as you suggested in point 1.

**Comment by pnikiel** [comment]
ad (2): but isn't it that you should ADD that define (UA_ENABLE_STATUSCODE_DESCRIPTIONS) somewhere to CMakeLists or prepare.py or whatever? Because right now we don't have it and you haven't added it either.

**Comment by parasxos** [comment]
It is by default enabled in open62541 CMakeLists: https://github.com/open62541/open62541/blob/master/CMakeLists.txt

**Comment by pnikiel** [comment]
Hi Paris,

I wrote a small test program:
`#include <statuscode.h>
#include <iostream>

int main()
{

    UaStatus s = OpcUa_BadResourceUnavailable;

    std::cout << s.toString().toUtf8() << std::endl;

    s = OpcUa_Good;

    std::cout << s.toString().toUtf8() << std::endl;

    s = 0x80122223;

    std::cout << s.toString().toUtf8() << std::endl;

}
`

here is the result obtained:

BadResourceUnavailable: An operating system resource is not available.
Good: Success / No error
Unknown: Unknown StatusCode

so this is almost perfect - I'd just ask you how difficult is if the last line would be:

Unknown: Unknown StatusCode( 0x80122223 )

**Comment by parasxos** [comment]
done

**Comment by pnikiel** [comment]
Hey I think that comparing the string for "Unknown" might not necessarily be reliable; if there is no other way can we just append the hex value to any status at its end? To produce something like this in my previous program:


BadResourceUnavailable: An operating system resource is not available. [0xAAAAAAAA..]
Good: Success / No error [0xBBBBBBBB]
Unknown: Unknown StatusCode [0xCCCCCCCC]

that would be enough and then we merge it.
Can I ask for this?

**Comment by parasxos** [comment]
Alrighty: Now, appending status code hex value uniformly to both known/unknown statuses.

**Comment by pnikiel** [comment]
Test results:
$ ./test 
BadResourceUnavailable: An operating system resource is not available. StatusCode (0x80040000)
Good: Success / No error StatusCode (0x0)
Unknown: Unknown StatusCode StatusCode (0x80122223)

Great ;-) Merging.
Welcome to the quasar ecosystem ;-)

**Pull request merged**
