### PR TITLE
for strings, match the unified automation API description

### PR DESCRIPTION
**Pull request by ben-farnham**
pull request containing problem & fix described in issue #21

### CODE REVIEW

**Comment by pnikiel** [comment]
@ben-farnham I believe that an improvement should be added.

You propose:

if (type == string) 
print_as_string();
else
print_generic();

I think it should be:
if (type == string && is_scalar)
print_as_string()
else
print_generic();

In other words, I think you put array of strings in wrong category.

**Comment by pnikiel** [comment]
But! Since our array support is at most primitive atm, i dont mind it to be done later as long as a jira or github ticket gets created.

**Comment by ben-farnham** [comment]
Thanks for the review - I added UaVariant::isScalarValue(). It's a bit dirtier than I'd hoped. An assumption is required because it appears that UaVariants containing scalar values do not always have their dimensions explicitly specified. Take a look at the branch now, see what you think.

**Comment by pnikiel** [comment]
To me it looks fine ;-)
I think you forgotten to push the header of UaVariant?
cause I don't see a new method in the header diff... but maybe i'm blind ;-)

**Comment by ben-farnham** [comment]
oops - header's there now.

**Comment by ben-farnham** [comment]
Happy for merge?

**Comment by pnikiel** [comment]
yes, go ahead.

**Comment by ben-farnham** [comment]
Just FYI: my motivation for this little bit of work. My unit tests were failing in the open62541-compat based builds of the iseg and caen servers where strings were passed then checked in uavariant form. Now **fixed** (blue == good)!

image

**Pull request merged**
